version: '3.3'

services:
  # frontend:
  #   image: scuba13/amacoon_web:latest
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - mynetwork

  backend:
    image: scuba13/amacoon_service:latest
    ports:
      - '8080:8080'
    depends_on:
      - mongo
    networks:
      - mynetwork

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - frontend
  #   networks:
  #     - mynetwork

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: amacoonroot
      MONGO_INITDB_ROOT_PASSWORD: amacoonrootpassword2022
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - mynetwork

  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: amacoonroot
      ME_CONFIG_MONGODB_ADMINPASSWORD: amacoonrootpassword2022
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: amacoon
      ME_CONFIG_BASICAUTH_PASSWORD: amacoon
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"

    depends_on:
      - mongo
    networks:
      - mynetwork

volumes:
  mongodb_data_container:

networks:
  mynetwork:
    driver: bridge
