version: '3.3'

services:
  # frontend:
  #   image: scuba13/amacoon_web:latest
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - mynetwork

  backend:
    image: scuba13/amacoon_service:latest
    ports:
      - '8080:8080'
    depends_on:
      - mongo
    networks:
      - mynetwork

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - frontend
  #   networks:
  #     - mynetwork

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootamacoon
      MONGO_INITDB_ROOT_PASSWORD: rootpasswordamacoon
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - mynetwork

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rootamacoon
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpasswordamacoon
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    networks:
      - mynetwork

volumes:
  mongodb_data_container:

networks:
  mynetwork:
    driver: bridge
