version: '3.3'

services:
  # frontend:
  #   image: scuba13/amacoon_web:latest
  #   ports:
  #     - "3000"
  #   networks:
  #     - mynetwork

  backend:
    image: scuba13/amacoon_service:latest
    ports:
      - '8080'
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - mynetwork
    publicEndpoint: true

networks:
  mynetwork:
    driver: bridge
